### ISSUE TITLE
Create jobs without rewards

### ISSUE THREAD

**Issue by cupOJoseph** [hai-on-op/core#16] opened 2023-10-03 00:58 UTC
https://github.com/hai-on-op/core/blob/c10c572b73ebdcd77a22e1b4e7f7b03483504e23/src/contracts/jobs/Job.sol#L39C26-L39C35

Currently, if there are no rewards available in the stabilityFeeTreasury, then jobs functions with the `reward` modifier will always fail. This could be a problem if someone wants to altruistically call jobs to keep the protocol moving

Jobs with the reward modifier will fail when:
- there's no rewards in the treasury
- the reward limit (per hour) has been reached
- when the balance of the treasury is below pullFundsMinThreshold

Suggestion:
create rewardless version of the jobs, which can be called without incentives.

**Comment by wei3erHase** [comment] 2023-10-03 11:45
Jobs are just the incentives layer for permisionless calls:
- if `AccountingJob.workPopDebtFromQueue(x)` fails (bc treasury has no funds)
- user can call `AccountingEngine.popDebtFromQueue(x)` (w/o reward)

All maintenance methods, by design, were chosen to be let permisionless.

**Comment by wei3erHase** [comment] 2023-11-29 11:03
Closing this issue 🥕

**Closed by wei3erHase** 2023-11-29 11:03 UTC
